version: '3.2'

services:
  database:
    container_name: enflujo-cms-database
    image: postgres:13
    restart: unless-stopped
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    networks:
      - enflujo-cms-network
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
  cache:
    # Nombre para docker.
    container_name: enflujo-cms-cache
    image: redis:6
    restart: unless-stopped
    networks:
      - enflujo-cms-network
  directus:
    container_name: enflujo-cms
    image: directus/directus
    restart: unless-stopped
    ports:
      - 4005:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    networks:
      - enflujo-cms-network
    depends_on:
      - cache
      - database
    environment:
      PUBLIC_URL: ${PUBLIC_URL}
      KEY: ${KEY}
      SECRET: ${SECRET}

      DB_CLIENT: 'pg'
      DB_HOST: 'enflujo-cms-database'
      DB_PORT: '5432'

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:${REDIS_PORT}'

      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_TRANSPORT: ${EMAIL_TRANSPORT}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
      EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}
      EMAIL_SMTP_SECURE: 'false'

      # OAuth para logearse desde una cuenta propia

      OAUTH_PROVIDERS: 'github'
      OAUTH_GITHUB_KEY: ${GITHUB_OAUTH_CLIENT_ID}
      OAUTH_GITHUB_SECRET: ${GITHUB_OAUTH_SECRET}

networks:
  enflujo-cms-network:

      